// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantPos.Api.Data;

#nullable disable

namespace RestaurantPos.Api.Data.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260928172951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RestaurantPos.Api.Data.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CancelledAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CgstPaise")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscountPaise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscountReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinalisedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinancialYear")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpenedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RoundOffPaise")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeqNo")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SettledAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SgstPaise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SubtotalPaise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableLabel")
                        .HasColumnType("TEXT");

                    b.Property<long>("TaxablePaise")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPaise")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BillNo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("FinancialYear", "SeqNo")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.BillLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LineTotalPaise")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPricePaise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ItemVariantId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("BillLines");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.ItemVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("PricePaise")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("ItemVariants");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShortCode");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountPaise")
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.RestaurantSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillFooter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FssaiNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GstRateBp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gstin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerPinHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            BillFooter = "Thank you! Visit again.",
                            FssaiNo = "",
                            GstRateBp = 500,
                            Gstin = "",
                            Name = "Your Restaurant",
                            Phone = "",
                            TaxMode = "Regular"
                        });
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.BillLine", b =>
                {
                    b.HasOne("RestaurantPos.Api.Data.Bill", null)
                        .WithMany("Lines")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantPos.Api.Data.ItemVariant", null)
                        .WithMany()
                        .HasForeignKey("ItemVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantPos.Api.Data.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.ItemVariant", b =>
                {
                    b.HasOne("RestaurantPos.Api.Data.MenuItem", null)
                        .WithMany("Variants")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.MenuItem", b =>
                {
                    b.HasOne("RestaurantPos.Api.Data.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.Payment", b =>
                {
                    b.HasOne("RestaurantPos.Api.Data.Bill", null)
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.Bill", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestaurantPos.Api.Data.MenuItem", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
